#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Vet")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertanimal(animal instance);
    partial void Updateanimal(animal instance);
    partial void Deleteanimal(animal instance);
    partial void Insertcitas(citas instance);
    partial void Updatecitas(citas instance);
    partial void Deletecitas(citas instance);
    partial void Insertdueño(dueño instance);
    partial void Updatedueño(dueño instance);
    partial void Deletedueño(dueño instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::capaDatos.Properties.Settings.Default.VetConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<animal> animal
		{
			get
			{
				return this.GetTable<animal>();
			}
		}
		
		public System.Data.Linq.Table<citas> citas
		{
			get
			{
				return this.GetTable<citas>();
			}
		}
		
		public System.Data.Linq.Table<dueño> dueño
		{
			get
			{
				return this.GetTable<dueño>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_loadAnimal")]
		public ISingleResult<sp_loadAnimalResult> sp_loadAnimal()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_loadAnimalResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_loadCitas")]
		public ISingleResult<sp_loadCitasResult> sp_loadCitas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_loadCitasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_loadDueño")]
		public ISingleResult<sp_loadDueñoResult> sp_loadDueño()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_loadDueñoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_crearDueño")]
		public int sp_crearDueño([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, telefono, correo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_crearAnimal")]
		public int sp_crearAnimal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string edad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string color, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dueño)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, edad, color, dueño);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_crearCita")]
		public int sp_crearCita([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string dueño, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string animal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha, dueño, animal);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_buscarCita")]
		public ISingleResult<sp_buscarCitaResult> sp_buscarCita([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCita)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCita);
			return ((ISingleResult<sp_buscarCitaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_repotarCita")]
		public int sp_repotarCita([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string tratamiento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tratamiento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_loadCitasFuturas")]
		public ISingleResult<sp_loadCitasFuturasResult> sp_loadCitasFuturas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_loadCitasFuturasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_reporteCitasAnimal")]
		public ISingleResult<sp_reporteCitasAnimalResult> sp_reporteCitasAnimal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_reporteCitasAnimalResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.animal")]
	public partial class animal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAnimal;
		
		private string _nomAnimal;
		
		private System.Nullable<int> _edad;
		
		private string _color;
		
		private System.Nullable<int> _Fk_Dueño;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAnimalChanging(int value);
    partial void OnidAnimalChanged();
    partial void OnnomAnimalChanging(string value);
    partial void OnnomAnimalChanged();
    partial void OnedadChanging(System.Nullable<int> value);
    partial void OnedadChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    partial void OnFk_DueñoChanging(System.Nullable<int> value);
    partial void OnFk_DueñoChanged();
    #endregion
		
		public animal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAnimal", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idAnimal
		{
			get
			{
				return this._idAnimal;
			}
			set
			{
				if ((this._idAnimal != value))
				{
					this.OnidAnimalChanging(value);
					this.SendPropertyChanging();
					this._idAnimal = value;
					this.SendPropertyChanged("idAnimal");
					this.OnidAnimalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomAnimal", DbType="VarChar(20)")]
		public string nomAnimal
		{
			get
			{
				return this._nomAnimal;
			}
			set
			{
				if ((this._nomAnimal != value))
				{
					this.OnnomAnimalChanging(value);
					this.SendPropertyChanging();
					this._nomAnimal = value;
					this.SendPropertyChanged("nomAnimal");
					this.OnnomAnimalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int")]
		public System.Nullable<int> edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(20)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Dueño", DbType="Int")]
		public System.Nullable<int> Fk_Dueño
		{
			get
			{
				return this._Fk_Dueño;
			}
			set
			{
				if ((this._Fk_Dueño != value))
				{
					this.OnFk_DueñoChanging(value);
					this.SendPropertyChanging();
					this._Fk_Dueño = value;
					this.SendPropertyChanged("Fk_Dueño");
					this.OnFk_DueñoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.citas")]
	public partial class citas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCita;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _FK_dueño;
		
		private System.Nullable<int> _FK_animal;
		
		private string _tratamiento;
		
		private string _concluido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCitaChanging(int value);
    partial void OnidCitaChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnFK_dueñoChanging(System.Nullable<int> value);
    partial void OnFK_dueñoChanged();
    partial void OnFK_animalChanging(System.Nullable<int> value);
    partial void OnFK_animalChanged();
    partial void OntratamientoChanging(string value);
    partial void OntratamientoChanged();
    partial void OnconcluidoChanging(string value);
    partial void OnconcluidoChanged();
    #endregion
		
		public citas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCita", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCita
		{
			get
			{
				return this._idCita;
			}
			set
			{
				if ((this._idCita != value))
				{
					this.OnidCitaChanging(value);
					this.SendPropertyChanging();
					this._idCita = value;
					this.SendPropertyChanged("idCita");
					this.OnidCitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_dueño", DbType="Int")]
		public System.Nullable<int> FK_dueño
		{
			get
			{
				return this._FK_dueño;
			}
			set
			{
				if ((this._FK_dueño != value))
				{
					this.OnFK_dueñoChanging(value);
					this.SendPropertyChanging();
					this._FK_dueño = value;
					this.SendPropertyChanged("FK_dueño");
					this.OnFK_dueñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_animal", DbType="Int")]
		public System.Nullable<int> FK_animal
		{
			get
			{
				return this._FK_animal;
			}
			set
			{
				if ((this._FK_animal != value))
				{
					this.OnFK_animalChanging(value);
					this.SendPropertyChanging();
					this._FK_animal = value;
					this.SendPropertyChanged("FK_animal");
					this.OnFK_animalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tratamiento", DbType="VarChar(MAX)")]
		public string tratamiento
		{
			get
			{
				return this._tratamiento;
			}
			set
			{
				if ((this._tratamiento != value))
				{
					this.OntratamientoChanging(value);
					this.SendPropertyChanging();
					this._tratamiento = value;
					this.SendPropertyChanged("tratamiento");
					this.OntratamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concluido", DbType="VarChar(2)")]
		public string concluido
		{
			get
			{
				return this._concluido;
			}
			set
			{
				if ((this._concluido != value))
				{
					this.OnconcluidoChanging(value);
					this.SendPropertyChanging();
					this._concluido = value;
					this.SendPropertyChanged("concluido");
					this.OnconcluidoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dueño")]
	public partial class dueño : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDueño;
		
		private string _nomDueño;
		
		private string _telefono;
		
		private string _correo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDueñoChanging(int value);
    partial void OnidDueñoChanged();
    partial void OnnomDueñoChanging(string value);
    partial void OnnomDueñoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    #endregion
		
		public dueño()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDueño", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDueño
		{
			get
			{
				return this._idDueño;
			}
			set
			{
				if ((this._idDueño != value))
				{
					this.OnidDueñoChanging(value);
					this.SendPropertyChanging();
					this._idDueño = value;
					this.SendPropertyChanged("idDueño");
					this.OnidDueñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomDueño", DbType="VarChar(20)")]
		public string nomDueño
		{
			get
			{
				return this._nomDueño;
			}
			set
			{
				if ((this._nomDueño != value))
				{
					this.OnnomDueñoChanging(value);
					this.SendPropertyChanging();
					this._nomDueño = value;
					this.SendPropertyChanged("nomDueño");
					this.OnnomDueñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(9)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(MAX)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_loadAnimalResult
	{
		
		private int _idAnimal;
		
		private string _nomAnimal;
		
		private System.Nullable<int> _edad;
		
		private string _color;
		
		private System.Nullable<int> _Fk_Dueño;
		
		public sp_loadAnimalResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAnimal", DbType="Int NOT NULL")]
		public int idAnimal
		{
			get
			{
				return this._idAnimal;
			}
			set
			{
				if ((this._idAnimal != value))
				{
					this._idAnimal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomAnimal", DbType="VarChar(20)")]
		public string nomAnimal
		{
			get
			{
				return this._nomAnimal;
			}
			set
			{
				if ((this._nomAnimal != value))
				{
					this._nomAnimal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int")]
		public System.Nullable<int> edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this._edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(20)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this._color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Dueño", DbType="Int")]
		public System.Nullable<int> Fk_Dueño
		{
			get
			{
				return this._Fk_Dueño;
			}
			set
			{
				if ((this._Fk_Dueño != value))
				{
					this._Fk_Dueño = value;
				}
			}
		}
	}
	
	public partial class sp_loadCitasResult
	{
		
		private int _idCita;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _FK_dueño;
		
		private System.Nullable<int> _FK_animal;
		
		private string _tratamiento;
		
		private string _concluido;
		
		public sp_loadCitasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCita", DbType="Int NOT NULL")]
		public int idCita
		{
			get
			{
				return this._idCita;
			}
			set
			{
				if ((this._idCita != value))
				{
					this._idCita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_dueño", DbType="Int")]
		public System.Nullable<int> FK_dueño
		{
			get
			{
				return this._FK_dueño;
			}
			set
			{
				if ((this._FK_dueño != value))
				{
					this._FK_dueño = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_animal", DbType="Int")]
		public System.Nullable<int> FK_animal
		{
			get
			{
				return this._FK_animal;
			}
			set
			{
				if ((this._FK_animal != value))
				{
					this._FK_animal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tratamiento", DbType="VarChar(MAX)")]
		public string tratamiento
		{
			get
			{
				return this._tratamiento;
			}
			set
			{
				if ((this._tratamiento != value))
				{
					this._tratamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concluido", DbType="VarChar(2)")]
		public string concluido
		{
			get
			{
				return this._concluido;
			}
			set
			{
				if ((this._concluido != value))
				{
					this._concluido = value;
				}
			}
		}
	}
	
	public partial class sp_loadDueñoResult
	{
		
		private int _idDueño;
		
		private string _nomDueño;
		
		private string _telefono;
		
		private string _correo;
		
		public sp_loadDueñoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDueño", DbType="Int NOT NULL")]
		public int idDueño
		{
			get
			{
				return this._idDueño;
			}
			set
			{
				if ((this._idDueño != value))
				{
					this._idDueño = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomDueño", DbType="VarChar(20)")]
		public string nomDueño
		{
			get
			{
				return this._nomDueño;
			}
			set
			{
				if ((this._nomDueño != value))
				{
					this._nomDueño = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(9)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(MAX)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
	}
	
	public partial class sp_buscarCitaResult
	{
		
		private int _idCita;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _FK_dueño;
		
		private System.Nullable<int> _FK_animal;
		
		private string _tratamiento;
		
		private string _concluido;
		
		public sp_buscarCitaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCita", DbType="Int NOT NULL")]
		public int idCita
		{
			get
			{
				return this._idCita;
			}
			set
			{
				if ((this._idCita != value))
				{
					this._idCita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_dueño", DbType="Int")]
		public System.Nullable<int> FK_dueño
		{
			get
			{
				return this._FK_dueño;
			}
			set
			{
				if ((this._FK_dueño != value))
				{
					this._FK_dueño = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_animal", DbType="Int")]
		public System.Nullable<int> FK_animal
		{
			get
			{
				return this._FK_animal;
			}
			set
			{
				if ((this._FK_animal != value))
				{
					this._FK_animal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tratamiento", DbType="VarChar(MAX)")]
		public string tratamiento
		{
			get
			{
				return this._tratamiento;
			}
			set
			{
				if ((this._tratamiento != value))
				{
					this._tratamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concluido", DbType="VarChar(2)")]
		public string concluido
		{
			get
			{
				return this._concluido;
			}
			set
			{
				if ((this._concluido != value))
				{
					this._concluido = value;
				}
			}
		}
	}
	
	public partial class sp_loadCitasFuturasResult
	{
		
		private int _idCita;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _FK_dueño;
		
		private System.Nullable<int> _FK_animal;
		
		private string _tratamiento;
		
		private string _concluido;
		
		public sp_loadCitasFuturasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCita", DbType="Int NOT NULL")]
		public int idCita
		{
			get
			{
				return this._idCita;
			}
			set
			{
				if ((this._idCita != value))
				{
					this._idCita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_dueño", DbType="Int")]
		public System.Nullable<int> FK_dueño
		{
			get
			{
				return this._FK_dueño;
			}
			set
			{
				if ((this._FK_dueño != value))
				{
					this._FK_dueño = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_animal", DbType="Int")]
		public System.Nullable<int> FK_animal
		{
			get
			{
				return this._FK_animal;
			}
			set
			{
				if ((this._FK_animal != value))
				{
					this._FK_animal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tratamiento", DbType="VarChar(MAX)")]
		public string tratamiento
		{
			get
			{
				return this._tratamiento;
			}
			set
			{
				if ((this._tratamiento != value))
				{
					this._tratamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concluido", DbType="VarChar(2)")]
		public string concluido
		{
			get
			{
				return this._concluido;
			}
			set
			{
				if ((this._concluido != value))
				{
					this._concluido = value;
				}
			}
		}
	}
	
	public partial class sp_reporteCitasAnimalResult
	{
		
		private int _idCita;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _FK_dueño;
		
		private System.Nullable<int> _FK_animal;
		
		private string _tratamiento;
		
		private string _concluido;
		
		public sp_reporteCitasAnimalResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCita", DbType="Int NOT NULL")]
		public int idCita
		{
			get
			{
				return this._idCita;
			}
			set
			{
				if ((this._idCita != value))
				{
					this._idCita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_dueño", DbType="Int")]
		public System.Nullable<int> FK_dueño
		{
			get
			{
				return this._FK_dueño;
			}
			set
			{
				if ((this._FK_dueño != value))
				{
					this._FK_dueño = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_animal", DbType="Int")]
		public System.Nullable<int> FK_animal
		{
			get
			{
				return this._FK_animal;
			}
			set
			{
				if ((this._FK_animal != value))
				{
					this._FK_animal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tratamiento", DbType="VarChar(MAX)")]
		public string tratamiento
		{
			get
			{
				return this._tratamiento;
			}
			set
			{
				if ((this._tratamiento != value))
				{
					this._tratamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concluido", DbType="VarChar(2)")]
		public string concluido
		{
			get
			{
				return this._concluido;
			}
			set
			{
				if ((this._concluido != value))
				{
					this._concluido = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
